/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projet;



public class App{


    public static void main(String[] args) {
        Graphic_Interface.launch(Graphic_Interface.class, args);    }
}
